{"id": 4520529296, "locations_block": ["The Peppermint Club", "Peppermint Club", "Pacific Design Center", "West Hollywood Library", "The Troubadour", "Spice Affair", "The Roxy", "The Comedy Store"], "criminals_count": 36383, "safety_status": "B"}
{"id": 4520529328, "locations_block": ["WeWork One Culver", "Father's Office"], "criminals_count": 28800, "safety_status": "B"}
{"id": 4520529360, "locations_block": ["Lodge Room Highland Park", "Lodge Room"], "criminals_count": 32407, "safety_status": "B"}
{"id": 4520529392, "locations_block": ["Edwards Alhambra Renaissance 14 & IMAX"], "criminals_count": 88, "safety_status": "A+"}
{"id": 4520529456, "locations_block": ["Los Angeles Celebrations Banquet Halls", "LA Celebrations Banquet Halls", "Dynasty Typewriter at The Hayworth", "Shatto Recreation Center & Park", "CCCM Mexican Center for Culture and Cinematic Arts", "MadAve", "Bootleg Theater", "Wilshire Boulevard Temple (Glazer Campus)"], "criminals_count": 159498, "safety_status": "D"}
{"id": 4520529488, "locations_block": ["Griffith Park, Crystal Springs Recreation Area", "Griffith Park Auditorium", "Autry Museum of the American West", "Griffith Park"], "criminals_count": 11901, "safety_status": "B"}
{"id": 4520529520, "locations_block": ["Beckman Auditorium", "Beckman Auditorium, Caltech", "Ice House Comedy Club", "USC Pacific Asia Museum"], "criminals_count": 5, "safety_status": "A+"}
{"id": 4520529552, "locations_block": ["Exchange LA", "Exchange L.A.", "The Last Bookstore", "Globe Theatre Los Angeles", "Seven Grand", "Central Library (then Industriel Farm for mixer)", "The Midnight Mission", "The Theatre at Ace Hotel", "Downtown Independent Theater", "515 South Flower Street", "The Emerson (Next door to Broad Museum)", "The Belasco Theater", "Walt Disney Concert Hall", "Los Angeles", "InterContinental Los Angeles Downtown", "South Park Center", "California Community Foundation", "Los Angeles City Hall - Tom Bradley Tower", "Hudson Loft", "Art Share L.A.", "A+D Architecture and Design Museum", "Microsoft Theater", "The Italian American Museum of Los Angeles", "Boomtown Brewery"], "criminals_count": 147473, "safety_status": "D"}
{"id": 4520530704, "locations_block": ["Globe Theatre Los Angeles", "Exchange LA", "Exchange L.A.", "Seven Grand", "The Theatre at Ace Hotel", "Central Library (then Industriel Farm for mixer)", "The Last Bookstore", "The Belasco Theater", "515 South Flower Street", "South Park Center", "InterContinental Los Angeles Downtown", "The Midnight Mission", "The Emerson (Next door to Broad Museum)", "Downtown Independent Theater", "Hudson Loft", "Walt Disney Concert Hall", "California Community Foundation", "Microsoft Theater", "Los Angeles", "Los Angeles City Hall - Tom Bradley Tower", "Art Share L.A.", "A+D Architecture and Design Museum"], "criminals_count": 153214, "safety_status": "D"}
{"id": 4520530736, "locations_block": ["Chang'an Restaurant", "Oh Shiny Paper Co"], "criminals_count": 2, "safety_status": "A+"}
{"id": 4520530768, "locations_block": ["Redgate Software", "Courtyard by Marriott Los Angeles Pasadena/Old Town", "USC Pacific Asia Museum"], "criminals_count": 167, "safety_status": "A"}
{"id": 4520530800, "locations_block": ["Heal One World", "Catch One"], "criminals_count": 97584, "safety_status": "C"}
{"id": 4520530832, "locations_block": ["Los Angeles City Hall - Tom Bradley Tower", "Los Angeles", "Downtown Independent Theater", "The Italian American Museum of Los Angeles", "Walt Disney Concert Hall", "The Emerson (Next door to Broad Museum)", "The Last Bookstore", "Boomtown Brewery", "Art Share L.A.", "California Community Foundation", "Exchange LA", "Exchange L.A.", "The Midnight Mission", "A+D Architecture and Design Museum", "The Institute for Art and Olfaction - Chinatown", "Central Library (then Industriel Farm for mixer)", "515 South Flower Street", "Seven Grand", "Globe Theatre Los Angeles", "InterContinental Los Angeles Downtown", "The Theatre at Ace Hotel"], "criminals_count": 124115, "safety_status": "D"}
{"id": 4520530864, "locations_block": ["Rose Bowl Stadium", "Rose Bowl"], "criminals_count": 217, "safety_status": "A"}
{"id": 4520530896, "locations_block": ["Avalon Hollywood", "APL Restaurant", "The Montalban Theatre", "Station 1640", "Liberate Hollywood", "Luchini Pizzeria & Bar", "6555 Hollywood Blvd", "Academy Nightclub", "Sound Nightclub", "The Complex Hollywood", "JAPAN HOUSE Los Angeles, Level 5 Salon", "Wanderlust Hollywood", "The Hollywood Roosevelt", "The Renberg Theatre", "Hollywood Forever Cemetery", "Assistance League Theatre", "Hollywood Casting and Film"], "criminals_count": 86486, "safety_status": "C"}
{"id": 4520530928, "locations_block": ["MUD Studio LA", "ARRI Inc. | Creative Space"], "criminals_count": 548, "safety_status": "A"}
{"id": 4520531056, "locations_block": ["Pacific Design Center", "West Hollywood Library", "The Peppermint Club", "Peppermint Club", "The Troubadour", "The Roxy", "The Comedy Store", "Spice Affair"], "criminals_count": 31064, "safety_status": "B"}
{"id": 4520531120, "locations_block": ["Liberate Hollywood", "Luchini Pizzeria & Bar", "Station 1640", "The Montalban Theatre", "APL Restaurant", "Avalon Hollywood", "6555 Hollywood Blvd", "Sound Nightclub", "Academy Nightclub", "The Complex Hollywood", "Wanderlust Hollywood", "JAPAN HOUSE Los Angeles, Level 5 Salon", "The Renberg Theatre", "The Hollywood Roosevelt", "Hollywood Forever Cemetery", "Hollywood Casting and Film", "Assistance League Theatre"], "criminals_count": 88599, "safety_status": "C"}
{"id": 4520531184, "locations_block": ["HaHa Comedy Club", "Vitello's"], "criminals_count": 45529, "safety_status": "B"}
{"id": 4520531216, "locations_block": ["The Beverly Hilton", "The Southern Temple"], "criminals_count": 18700, "safety_status": "B"}
{"id": 4520531248, "locations_block": ["Petersen Automotive Museum", "Wood Ranch", "Spice Affair"], "criminals_count": 66821, "safety_status": "C"}
{"id": 4520531280, "locations_block": ["Art Share L.A.", "A+D Architecture and Design Museum", "Boomtown Brewery", "The Midnight Mission", "Los Angeles", "Downtown Independent Theater", "Los Angeles City Hall - Tom Bradley Tower", "The Last Bookstore", "The Italian American Museum of Los Angeles", "Exchange L.A.", "Exchange LA", "Walt Disney Concert Hall", "The Emerson (Next door to Broad Museum)", "Globe Theatre Los Angeles", "Central Library (then Industriel Farm for mixer)", "Seven Grand"], "criminals_count": 116572, "safety_status": "D"}
{"id": 4520531312, "locations_block": ["Wood Ranch", "Petersen Automotive Museum", "melrose lightspace", "Spice Affair"], "criminals_count": 62769, "safety_status": "C"}
{"id": 4520531376, "locations_block": ["Hudson Loft", "South Park Center", "Microsoft Theater", "The Belasco Theater", "The Theatre at Ace Hotel", "InterContinental Los Angeles Downtown", "Globe Theatre Los Angeles", "Seven Grand", "Pico Union Project", "Central Library (then Industriel Farm for mixer)", "Casa Vertigo", "515 South Flower Street", "Exchange LA", "Exchange L.A.", "The Last Bookstore", "The Midnight Mission", "The Emerson (Next door to Broad Museum)", "California Community Foundation"], "criminals_count": 174729, "safety_status": "D"}
{"id": 4520531408, "locations_block": ["Courtyard by Marriott Los Angeles Pasadena/Old Town", "Redgate Software", "USC Pacific Asia Museum", "Ice House Comedy Club"], "criminals_count": 6, "safety_status": "A+"}
{"id": 4520531440, "locations_block": ["Embassy Suites by Hilton Los Angeles Glendale", "Embassy Suites Glendale- Los Angeles"], "criminals_count": 1439, "safety_status": "A"}
{"id": 4520531472, "locations_block": ["Los Globos", "MadAve", "Bootleg Theater"], "criminals_count": 111905, "safety_status": "D"}
{"id": 4520531504, "locations_block": ["REV Winery & Brewing Company"], "criminals_count": 4, "safety_status": "A+"}
{"id": 4520531824, "locations_block": ["Shatto Recreation Center & Park", "Los Angeles Celebrations Banquet Halls", "LA Celebrations Banquet Halls", "MadAve", "Dynasty Typewriter at The Hayworth", "CCCM Mexican Center for Culture and Cinematic Arts", "Wilshire Boulevard Temple (Glazer Campus)", "Bootleg Theater"], "criminals_count": 153928, "safety_status": "D"}
{"id": 4520531856, "locations_block": ["Rose Bowl Stadium", "Rose Bowl"], "criminals_count": 217, "safety_status": "A"}
{"id": 4520531888, "locations_block": ["Seal Beach Center for Spiritual Living"], "criminals_count": 1, "safety_status": "A+"}
{"id": 4520531920, "locations_block": ["Southbay SBDC hosted by El Camino College Business Training Center "], "criminals_count": 72, "safety_status": "A+"}
{"id": 4520532080, "locations_block": ["Redondo Beach Performing Arts Center"], "criminals_count": 24, "safety_status": "A+"}
{"id": 4520532208, "locations_block": ["melrose lightspace", "Wood Ranch", "Hollywood Casting and Film", "The Renberg Theatre"], "criminals_count": 74939, "safety_status": "C"}
{"id": 4520532400, "locations_block": ["Diamond Way Buddhist Center Los Angeles", "EDGE Studios & Grip", "Edge Studios & Grip"], "criminals_count": 87655, "safety_status": "C"}
{"id": 4520532592, "locations_block": ["Father's Office", "WeWork One Culver"], "criminals_count": 39839, "safety_status": "B"}
{"id": 4520532656, "locations_block": ["Embassy Suites by Hilton Los Angeles Glendale", "Embassy Suites Glendale- Los Angeles"], "criminals_count": 1439, "safety_status": "A"}
{"id": 4520532688, "locations_block": ["West LA", "Colby Rebel Spirit Center", "Neat"], "criminals_count": 43700, "safety_status": "B"}
{"id": 4520532912, "locations_block": ["2439 California Ave"], "criminals_count": 15138, "safety_status": "B"}
{"id": 4520533552, "locations_block": ["Westchester United Methodist Church"], "criminals_count": 30858, "safety_status": "B"}
{"id": 4520533648, "locations_block": ["Catch One", "Heal One World", "EDGE Studios & Grip", "Edge Studios & Grip"], "criminals_count": 90669, "safety_status": "C"}
{"id": 4520533680, "locations_block": ["Academy Nightclub", "APL Restaurant", "The Montalban Theatre", "Avalon Hollywood", "Liberate Hollywood", "Station 1640", "Luchini Pizzeria & Bar", "Assistance League Theatre", "6555 Hollywood Blvd", "Hollywood Forever Cemetery", "The Complex Hollywood", "Sound Nightclub", "Wanderlust Hollywood", "JAPAN HOUSE Los Angeles, Level 5 Salon", "The Renberg Theatre"], "criminals_count": 94174, "safety_status": "C"}
{"id": 4520533712, "locations_block": ["Hollywood Forever Cemetery", "Assistance League Theatre", "The Complex Hollywood", "Academy Nightclub", "The Montalban Theatre", "APL Restaurant", "Liberate Hollywood", "Luchini Pizzeria & Bar", "Station 1640", "Avalon Hollywood", "The Renberg Theatre", "6555 Hollywood Blvd"], "criminals_count": 116053, "safety_status": "D"}
{"id": 4520533744, "locations_block": ["Walt Disney Concert Hall", "The Emerson (Next door to Broad Museum)", "California Community Foundation", "Downtown Independent Theater", "Los Angeles", "Los Angeles City Hall - Tom Bradley Tower", "The Last Bookstore", "515 South Flower Street", "Central Library (then Industriel Farm for mixer)", "Exchange LA", "Exchange L.A.", "Seven Grand", "InterContinental Los Angeles Downtown", "Globe Theatre Los Angeles", "The Italian American Museum of Los Angeles", "The Midnight Mission", "The Institute for Art and Olfaction - Chinatown", "The Theatre at Ace Hotel", "Art Share L.A.", "Boomtown Brewery", "The Belasco Theater", "A+D Architecture and Design Museum", "South Park Center"], "criminals_count": 142287, "safety_status": "D"}
{"id": 4520533776, "locations_block": ["Los Angeles Memorial Coliseum", "California African American Museum"], "criminals_count": 124234, "safety_status": "D"}
{"id": 4520533808, "locations_block": ["Los Angeles Celebrations Banquet Halls", "LA Celebrations Banquet Halls", "Dynasty Typewriter at The Hayworth", "Shatto Recreation Center & Park", "CCCM Mexican Center for Culture and Cinematic Arts", "MadAve", "Bootleg Theater", "Wilshire Boulevard Temple (Glazer Campus)"], "criminals_count": 159498, "safety_status": "D"}
{"id": 4520533840, "locations_block": ["The Roxy", "The Troubadour", "West Hollywood Library", "Pacific Design Center", "The Comedy Store", "Peppermint Club", "The Peppermint Club"], "criminals_count": 17600, "safety_status": "B"}
{"id": 4520533872, "locations_block": ["Studio Maesto"], "criminals_count": 7140, "safety_status": "A"}
{"id": 4520533904, "locations_block": ["Exchange LA", "Exchange L.A.", "The Last Bookstore", "Globe Theatre Los Angeles", "Seven Grand", "Central Library (then Industriel Farm for mixer)", "The Midnight Mission", "The Theatre at Ace Hotel", "Downtown Independent Theater", "515 South Flower Street", "The Emerson (Next door to Broad Museum)", "The Belasco Theater", "Walt Disney Concert Hall", "Los Angeles", "InterContinental Los Angeles Downtown", "South Park Center", "California Community Foundation", "Los Angeles City Hall - Tom Bradley Tower", "Hudson Loft", "Art Share L.A.", "A+D Architecture and Design Museum", "Microsoft Theater", "The Italian American Museum of Los Angeles", "Boomtown Brewery"], "criminals_count": 147473, "safety_status": "D"}
{"id": 4520533936, "locations_block": ["Griffith Park", "Griffith Park Auditorium", "Autry Museum of the American West", "Griffith Park, Crystal Springs Recreation Area"], "criminals_count": 7748, "safety_status": "A"}
{"id": 4520533968, "locations_block": ["Beckman Auditorium, Caltech", "Beckman Auditorium", "Ice House Comedy Club", "USC Pacific Asia Museum"], "criminals_count": 5, "safety_status": "A+"}
{"id": 4520534000, "locations_block": ["The Peppermint Club", "Peppermint Club", "Pacific Design Center", "West Hollywood Library", "The Troubadour", "Spice Affair", "The Roxy", "The Comedy Store"], "criminals_count": 36383, "safety_status": "B"}
{"id": 4520534064, "locations_block": ["Lodge Room Highland Park", "Lodge Room"], "criminals_count": 32407, "safety_status": "B"}
{"id": 4520534096, "locations_block": ["The Troubadour", "West Hollywood Library", "Pacific Design Center", "The Roxy", "Peppermint Club", "The Peppermint Club"], "criminals_count": 22787, "safety_status": "B"}
{"id": 4520534448, "locations_block": ["Vitello's", "HaHa Comedy Club"], "criminals_count": 47507, "safety_status": "B"}
{"id": 4520534576, "locations_block": ["Sound Nightclub", "6555 Hollywood Blvd", "JAPAN HOUSE Los Angeles, Level 5 Salon", "The Hollywood Roosevelt", "Wanderlust Hollywood", "Luchini Pizzeria & Bar", "Station 1640", "Liberate Hollywood", "Avalon Hollywood", "The Montalban Theatre", "The Renberg Theatre", "APL Restaurant", "Hollywood Casting and Film", "The Complex Hollywood", "Academy Nightclub"], "criminals_count": 82074, "safety_status": "C"}
{"id": 4520534672, "locations_block": ["Semel Institute Auditorium", "University of California, Los Angeles", "James West Alumni Center", "Hosted by UCLA - Carnesale Commons", "Colby Rebel Spirit Center"], "criminals_count": 33526, "safety_status": "B"}
{"id": 4520534736, "locations_block": ["Central Library (then Industriel Farm for mixer)", "Seven Grand", "515 South Flower Street", "Globe Theatre Los Angeles", "InterContinental Los Angeles Downtown", "Exchange L.A.", "Exchange LA", "The Last Bookstore", "The Emerson (Next door to Broad Museum)", "The Theatre at Ace Hotel", "California Community Foundation", "Walt Disney Concert Hall", "The Belasco Theater", "Downtown Independent Theater", "South Park Center", "The Midnight Mission", "Hudson Loft", "Microsoft Theater", "Los Angeles", "Los Angeles City Hall - Tom Bradley Tower", "Pico Union Project", "Art Share L.A."], "criminals_count": 158549, "safety_status": "D"}
{"id": 4520534768, "locations_block": ["James West Alumni Center", "University of California, Los Angeles", "Semel Institute Auditorium", "Hosted by UCLA - Carnesale Commons"], "criminals_count": 28573, "safety_status": "B"}
{"id": 4520534864, "locations_block": ["The Last Bookstore", "Exchange LA", "Exchange L.A.", "Downtown Independent Theater", "Globe Theatre Los Angeles", "Central Library (then Industriel Farm for mixer)", "Seven Grand", "The Emerson (Next door to Broad Museum)", "The Midnight Mission", "Los Angeles", "Walt Disney Concert Hall", "515 South Flower Street", "Los Angeles City Hall - Tom Bradley Tower", "The Theatre at Ace Hotel", "California Community Foundation", "InterContinental Los Angeles Downtown", "The Belasco Theater", "Art Share L.A.", "A+D Architecture and Design Museum", "South Park Center", "The Italian American Museum of Los Angeles", "Hudson Loft", "Boomtown Brewery", "Microsoft Theater"], "criminals_count": 143829, "safety_status": "D"}
{"id": 4520534960, "locations_block": ["The Renberg Theatre", "Hollywood Casting and Film", "Wanderlust Hollywood", "The Complex Hollywood", "Sound Nightclub", "The Hollywood Roosevelt", "JAPAN HOUSE Los Angeles, Level 5 Salon", "6555 Hollywood Blvd", "Luchini Pizzeria & Bar", "Liberate Hollywood", "Station 1640", "The Montalban Theatre", "APL Restaurant", "Avalon Hollywood", "Hollywood Forever Cemetery", "melrose lightspace", "Academy Nightclub"], "criminals_count": 91429, "safety_status": "C"}
{"id": 4520534992, "locations_block": ["Wilshire Boulevard Temple (Glazer Campus)", "Shatto Recreation Center & Park", "Los Angeles Celebrations Banquet Halls", "LA Celebrations Banquet Halls"], "criminals_count": 128640, "safety_status": "D"}
{"id": 4520535088, "locations_block": ["Edge Studios & Grip", "EDGE Studios & Grip", "Diamond Way Buddhist Center Los Angeles", "Catch One"], "criminals_count": 72291, "safety_status": "C"}
{"id": 4520535152, "locations_block": ["South Park Center", "The Belasco Theater", "Hudson Loft", "The Theatre at Ace Hotel", "Microsoft Theater", "Globe Theatre Los Angeles", "Seven Grand", "InterContinental Los Angeles Downtown", "Central Library (then Industriel Farm for mixer)", "Exchange LA", "Exchange L.A.", "515 South Flower Street", "The Last Bookstore", "Pico Union Project", "The Midnight Mission", "Casa Vertigo", "The Emerson (Next door to Broad Museum)", "California Community Foundation", "Downtown Independent Theater", "Walt Disney Concert Hall"], "criminals_count": 167353, "safety_status": "D"}
{"id": 4520535184, "locations_block": ["University of California, Los Angeles", "James West Alumni Center", "Semel Institute Auditorium", "Hosted by UCLA - Carnesale Commons"], "criminals_count": 30499, "safety_status": "B"}
{"id": 4520535344, "locations_block": ["Renaissance Los Angeles Airport Hotel", "Ahmanson Recruit Training Center"], "criminals_count": 25216, "safety_status": "B"}
{"id": 4520535600, "locations_block": ["CCCM Mexican Center for Culture and Cinematic Arts", "Dynasty Typewriter at The Hayworth", "LA Celebrations Banquet Halls", "Los Angeles Celebrations Banquet Halls", "Bootleg Theater", "Shatto Recreation Center & Park", "Pico Union Project", "MadAve"], "criminals_count": 163179, "safety_status": "D"}
{"id": 4520535632, "locations_block": ["California African American Museum", "Los Angeles Memorial Coliseum"], "criminals_count": 127785, "safety_status": "D"}
{"id": 4520535728, "locations_block": ["Luchini Pizzeria & Bar", "Liberate Hollywood", "Station 1640", "The Montalban Theatre", "APL Restaurant", "Avalon Hollywood", "6555 Hollywood Blvd", "Sound Nightclub", "Academy Nightclub", "The Complex Hollywood", "Wanderlust Hollywood", "JAPAN HOUSE Los Angeles, Level 5 Salon", "The Renberg Theatre", "The Hollywood Roosevelt", "Hollywood Casting and Film", "Hollywood Forever Cemetery", "Assistance League Theatre"], "criminals_count": 87833, "safety_status": "C"}
{"id": 4520535760, "locations_block": ["The Foundation Center"], "criminals_count": 16379, "safety_status": "B"}
{"id": 4520535920, "locations_block": ["A+D Architecture and Design Museum", "Art Share L.A.", "Boomtown Brewery", "The Midnight Mission", "Downtown Independent Theater", "Los Angeles", "Los Angeles City Hall - Tom Bradley Tower", "The Last Bookstore", "The Italian American Museum of Los Angeles", "Exchange L.A.", "Exchange LA", "Globe Theatre Los Angeles", "Walt Disney Concert Hall", "The Emerson (Next door to Broad Museum)", "Seven Grand"], "criminals_count": 115662, "safety_status": "D"}
{"id": 4520536016, "locations_block": ["The Clubhouse Mainstage", "Assistance League Theatre"], "criminals_count": 76848, "safety_status": "C"}
{"id": 4520536048, "locations_block": ["Wanderlust Hollywood", "The Renberg Theatre", "Hollywood Casting and Film", "Sound Nightclub", "The Hollywood Roosevelt", "JAPAN HOUSE Los Angeles, Level 5 Salon", "6555 Hollywood Blvd", "The Complex Hollywood", "Luchini Pizzeria & Bar", "Liberate Hollywood", "Station 1640", "The Montalban Theatre", "Avalon Hollywood", "APL Restaurant", "Academy Nightclub"], "criminals_count": 85133, "safety_status": "C"}
{"id": 104036269904, "locations_block": ["6555 Hollywood Blvd", "Sound Nightclub", "Luchini Pizzeria & Bar", "Station 1640", "Liberate Hollywood", "Avalon Hollywood", "The Montalban Theatre", "APL Restaurant", "JAPAN HOUSE Los Angeles, Level 5 Salon", "Wanderlust Hollywood", "The Hollywood Roosevelt", "The Renberg Theatre", "The Complex Hollywood", "Academy Nightclub", "Hollywood Casting and Film", "Hollywood Forever Cemetery"], "criminals_count": 83930, "safety_status": "C"}
{"id": 104036270000, "locations_block": ["USC Pacific Asia Museum", "Courtyard by Marriott Los Angeles Pasadena/Old Town", "Ice House Comedy Club", "Redgate Software", "Beckman Auditorium", "Beckman Auditorium, Caltech"], "criminals_count": 5, "safety_status": "A+"}
{"id": 104036268944, "locations_block": ["Ice House Comedy Club", "Beckman Auditorium", "Beckman Auditorium, Caltech", "USC Pacific Asia Museum", "Courtyard by Marriott Los Angeles Pasadena/Old Town"], "criminals_count": 5, "safety_status": "A+"}
{"id": 104036268944, "locations_block": ["Spice Affair", "Peppermint Club", "The Peppermint Club", "Petersen Automotive Museum", "Pacific Design Center", "West Hollywood Library", "Wood Ranch"], "criminals_count": 48790, "safety_status": "B"}
{"id": 104036270000, "locations_block": ["Hollywood Casting and Film", "The Renberg Theatre", "Wanderlust Hollywood", "The Complex Hollywood", "The Hollywood Roosevelt", "Sound Nightclub", "JAPAN HOUSE Los Angeles, Level 5 Salon", "6555 Hollywood Blvd", "Luchini Pizzeria & Bar", "Liberate Hollywood", "Station 1640", "melrose lightspace", "The Montalban Theatre", "APL Restaurant", "Avalon Hollywood"], "criminals_count": 89335, "safety_status": "C"}
{"id": 104036269904, "locations_block": ["Vero Pilates", "223 Grand Ave"], "criminals_count": 56, "safety_status": "A+"}
{"id": 104036268944, "locations_block": ["The Emerson (Next door to Broad Museum)", "Walt Disney Concert Hall", "California Community Foundation", "515 South Flower Street", "The Last Bookstore", "Downtown Independent Theater", "Central Library (then Industriel Farm for mixer)", "Los Angeles", "Seven Grand", "Los Angeles City Hall - Tom Bradley Tower", "Exchange LA", "Exchange L.A.", "InterContinental Los Angeles Downtown", "Globe Theatre Los Angeles", "The Midnight Mission", "The Theatre at Ace Hotel", "The Italian American Museum of Los Angeles", "The Belasco Theater", "The Institute for Art and Olfaction - Chinatown", "Art Share L.A.", "South Park Center", "Boomtown Brewery", "A+D Architecture and Design Museum", "Microsoft Theater", "Hudson Loft"], "criminals_count": 145050, "safety_status": "D"}
{"id": 104036268944, "locations_block": ["The Hollywood Roosevelt", "JAPAN HOUSE Los Angeles, Level 5 Salon", "Sound Nightclub", "Wanderlust Hollywood", "6555 Hollywood Blvd", "The Renberg Theatre", "Hollywood Casting and Film", "Luchini Pizzeria & Bar", "Station 1640", "Liberate Hollywood", "Avalon Hollywood", "The Montalban Theatre", "The Complex Hollywood", "APL Restaurant"], "criminals_count": 76970, "safety_status": "C"}
{"id": 104036268944, "locations_block": ["James R. Armstrong Theatre"], "criminals_count": 1, "safety_status": "A+"}
{"id": 104036268944, "locations_block": ["Autry Museum of the American West", "Griffith Park Auditorium", "Griffith Park, Crystal Springs Recreation Area", "Griffith Park"], "criminals_count": 3752, "safety_status": "A"}
{"id": 104036270000, "locations_block": ["West Hollywood Library", "Pacific Design Center", "The Troubadour", "Peppermint Club", "The Peppermint Club", "The Roxy", "The Comedy Store", "Spice Affair"], "criminals_count": 29918, "safety_status": "B"}
{"id": 104036270000, "locations_block": ["InterContinental Los Angeles Downtown", "515 South Flower Street", "Central Library (then Industriel Farm for mixer)", "Seven Grand", "Globe Theatre Los Angeles", "California Community Foundation", "Microsoft Theater", "The Theatre at Ace Hotel", "The Emerson (Next door to Broad Museum)", "The Belasco Theater", "Exchange LA", "Exchange L.A.", "Hudson Loft", "South Park Center", "The Last Bookstore", "Walt Disney Concert Hall", "Downtown Independent Theater", "Pico Union Project", "The Midnight Mission", "Los Angeles", "Los Angeles City Hall - Tom Bradley Tower"], "criminals_count": 168974, "safety_status": "D"}
{"id": 103691109360, "locations_block": ["Downtown Independent Theater", "Los Angeles", "Los Angeles City Hall - Tom Bradley Tower", "The Last Bookstore", "Walt Disney Concert Hall", "The Emerson (Next door to Broad Museum)", "Exchange LA", "Exchange L.A.", "The Midnight Mission", "Central Library (then Industriel Farm for mixer)", "Globe Theatre Los Angeles", "Art Share L.A.", "Seven Grand", "California Community Foundation", "The Italian American Museum of Los Angeles", "515 South Flower Street", "A+D Architecture and Design Museum", "Boomtown Brewery", "The Theatre at Ace Hotel", "InterContinental Los Angeles Downtown", "The Institute for Art and Olfaction - Chinatown", "The Belasco Theater", "South Park Center"], "criminals_count": 130808, "safety_status": "D"}
{"id": 103691109360, "locations_block": ["Colby Rebel Spirit Center", "West LA", "Semel Institute Auditorium"], "criminals_count": 45118, "safety_status": "B"}
{"id": 103691109360, "locations_block": ["The Midnight Mission", "Exchange LA", "Exchange L.A.", "The Last Bookstore", "Downtown Independent Theater", "Globe Theatre Los Angeles", "A+D Architecture and Design Museum", "Art Share L.A.", "Los Angeles", "The Theatre at Ace Hotel", "Seven Grand", "Central Library (then Industriel Farm for mixer)", "Los Angeles City Hall - Tom Bradley Tower", "The Emerson (Next door to Broad Museum)", "The Belasco Theater", "Walt Disney Concert Hall", "515 South Flower Street", "Boomtown Brewery", "South Park Center", "InterContinental Los Angeles Downtown", "California Community Foundation", "The Italian American Museum of Los Angeles", "Hudson Loft", "1720 E 16th St"], "criminals_count": 130398, "safety_status": "D"}
{"id": 104036268944, "locations_block": ["1720 E 16th St", "The Midnight Mission"], "criminals_count": 107331, "safety_status": "D"}
{"id": 104036268944, "locations_block": ["Bootleg Theater", "CCCM Mexican Center for Culture and Cinematic Arts", "Dynasty Typewriter at The Hayworth", "Los Angeles Celebrations Banquet Halls", "LA Celebrations Banquet Halls", "Los Globos", "Shatto Recreation Center & Park", "MadAve"], "criminals_count": 155130, "safety_status": "D"}
{"id": 104036268944, "locations_block": ["The Theatre at Ace Hotel", "The Belasco Theater", "Globe Theatre Los Angeles", "South Park Center", "Seven Grand", "Exchange L.A.", "Exchange LA", "Central Library (then Industriel Farm for mixer)", "Hudson Loft", "InterContinental Los Angeles Downtown", "The Last Bookstore", "515 South Flower Street", "Microsoft Theater", "The Midnight Mission", "The Emerson (Next door to Broad Museum)", "Downtown Independent Theater", "California Community Foundation", "Walt Disney Concert Hall", "Los Angeles", "Pico Union Project", "Los Angeles City Hall - Tom Bradley Tower"], "criminals_count": 159544, "safety_status": "D"}
{"id": 104036270000, "locations_block": ["Dynasty Typewriter at The Hayworth", "CCCM Mexican Center for Culture and Cinematic Arts", "LA Celebrations Banquet Halls", "Los Angeles Celebrations Banquet Halls", "Bootleg Theater", "Shatto Recreation Center & Park", "Pico Union Project", "MadAve"], "criminals_count": 164339, "safety_status": "D"}
{"id": 104036270000, "locations_block": ["Boomtown Brewery", "Art Share L.A.", "A+D Architecture and Design Museum", "The Italian American Museum of Los Angeles", "Los Angeles City Hall - Tom Bradley Tower", "Los Angeles", "Downtown Independent Theater", "The Midnight Mission", "The Institute for Art and Olfaction - Chinatown", "The Last Bookstore", "Walt Disney Concert Hall", "The Emerson (Next door to Broad Museum)", "Exchange L.A.", "Exchange LA"], "criminals_count": 110307, "safety_status": "D"}
{"id": 104036268944, "locations_block": ["The Comedy Store", "The Roxy", "Pacific Design Center", "West Hollywood Library", "Peppermint Club", "The Peppermint Club"], "criminals_count": 33783, "safety_status": "B"}
{"id": 103691109360, "locations_block": ["Griffith Park Auditorium", "Griffith Park, Crystal Springs Recreation Area", "Griffith Park", "Autry Museum of the American West"], "criminals_count": 12425, "safety_status": "B"}
{"id": 103691109360, "locations_block": ["Neat", "West LA"], "criminals_count": 37605, "safety_status": "B"}
{"id": 103691109360, "locations_block": ["Long Beach Marriott"], "criminals_count": 16, "safety_status": "A+"}
{"id": 104036269872, "locations_block": ["Microsoft Theater", "Hudson Loft", "Pico Union Project", "South Park Center", "The Belasco Theater", "InterContinental Los Angeles Downtown", "The Theatre at Ace Hotel", "Seven Grand", "Central Library (then Industriel Farm for mixer)", "515 South Flower Street", "Casa Vertigo", "Globe Theatre Los Angeles", "Exchange LA", "Exchange L.A.", "California Community Foundation", "The Last Bookstore", "The Emerson (Next door to Broad Museum)"], "criminals_count": 178819, "safety_status": "D"}
{"id": 104036268944, "locations_block": ["The Montalban Theatre", "APL Restaurant", "Liberate Hollywood", "Station 1640", "Avalon Hollywood", "Luchini Pizzeria & Bar", "Academy Nightclub", "6555 Hollywood Blvd", "Sound Nightclub", "The Complex Hollywood", "Wanderlust Hollywood", "JAPAN HOUSE Los Angeles, Level 5 Salon", "The Renberg Theatre", "Hollywood Forever Cemetery", "The Hollywood Roosevelt", "Assistance League Theatre", "Hollywood Casting and Film"], "criminals_count": 90156, "safety_status": "C"}
{"id": 104036268944, "locations_block": ["Assistance League Theatre", "Hollywood Forever Cemetery", "Academy Nightclub", "APL Restaurant", "The Montalban Theatre", "Avalon Hollywood", "Liberate Hollywood", "Station 1640", "The Clubhouse Mainstage", "Luchini Pizzeria & Bar"], "criminals_count": 107111, "safety_status": "D"}
{"id": 104036269872, "locations_block": ["Los Angeles Community Clinic Resource Center"], "criminals_count": 48139, "safety_status": "B"}
{"id": 104036269872, "locations_block": ["Seven Grand", "Central Library (then Industriel Farm for mixer)", "Globe Theatre Los Angeles", "515 South Flower Street", "Exchange L.A.", "Exchange LA", "InterContinental Los Angeles Downtown", "The Theatre at Ace Hotel", "The Last Bookstore", "The Belasco Theater", "The Emerson (Next door to Broad Museum)", "South Park Center", "California Community Foundation", "Walt Disney Concert Hall", "Downtown Independent Theater", "Hudson Loft", "The Midnight Mission", "Microsoft Theater", "Los Angeles", "Los Angeles City Hall - Tom Bradley Tower", "Pico Union Project", "Art Share L.A.", "A+D Architecture and Design Museum"], "criminals_count": 158806, "safety_status": "D"}
{"id": 104036269392, "locations_block": ["515 South Flower Street", "Central Library (then Industriel Farm for mixer)", "InterContinental Los Angeles Downtown", "Seven Grand", "California Community Foundation", "The Emerson (Next door to Broad Museum)", "Globe Theatre Los Angeles", "Walt Disney Concert Hall", "The Last Bookstore", "Exchange L.A.", "Exchange LA", "The Theatre at Ace Hotel", "Downtown Independent Theater", "The Belasco Theater", "Microsoft Theater", "South Park Center", "Los Angeles", "Hudson Loft", "Los Angeles City Hall - Tom Bradley Tower", "The Midnight Mission", "Pico Union Project"], "criminals_count": 160630, "safety_status": "D"}
{"id": 104036269392, "locations_block": ["Plaza Americana"], "criminals_count": 25988, "safety_status": "B"}
{"id": 104036269392, "locations_block": ["Harley-Davidson\u00aeof Glendale"], "criminals_count": 19367, "safety_status": "B"}
{"id": 103691109360, "locations_block": ["Pico Union Project", "Microsoft Theater", "Casa Vertigo", "Hudson Loft", "South Park Center", "InterContinental Los Angeles Downtown", "The Belasco Theater", "Dynasty Typewriter at The Hayworth", "CCCM Mexican Center for Culture and Cinematic Arts", "The Theatre at Ace Hotel", "515 South Flower Street", "Seven Grand", "Central Library (then Industriel Farm for mixer)"], "criminals_count": 180675, "safety_status": "D"}
{"id": 104036270000, "locations_block": ["Hosted by UCLA - Carnesale Commons", "James West Alumni Center", "University of California, Los Angeles", "Semel Institute Auditorium"], "criminals_count": 26106, "safety_status": "B"}
{"id": 104036269392, "locations_block": ["The Institute for Art and Olfaction - Chinatown", "The Italian American Museum of Los Angeles", "Los Angeles City Hall - Tom Bradley Tower", "Los Angeles", "Walt Disney Concert Hall", "Boomtown Brewery", "Downtown Independent Theater", "The Emerson (Next door to Broad Museum)", "California Community Foundation"], "criminals_count": 104902, "safety_status": "D"}
{"id": 104036269392, "locations_block": ["International School of Los Angeles - Burbank Campus"], "criminals_count": 1116, "safety_status": "A"}
{"id": 104036270000, "locations_block": ["California Community Foundation", "The Emerson (Next door to Broad Museum)", "Walt Disney Concert Hall", "515 South Flower Street", "Central Library (then Industriel Farm for mixer)", "InterContinental Los Angeles Downtown", "Seven Grand", "The Last Bookstore", "Downtown Independent Theater", "Los Angeles", "Exchange L.A.", "Exchange LA", "Los Angeles City Hall - Tom Bradley Tower", "Globe Theatre Los Angeles", "The Theatre at Ace Hotel", "The Italian American Museum of Los Angeles", "The Midnight Mission", "The Belasco Theater", "Microsoft Theater", "The Institute for Art and Olfaction - Chinatown", "South Park Center", "Hudson Loft"], "criminals_count": 151657, "safety_status": "D"}
{"id": 104036270000, "locations_block": ["Tamayo Restaurant and Art Gallery"], "criminals_count": 8, "safety_status": "A+"}
{"id": 104036269392, "locations_block": ["223 Grand Ave", "Vero Pilates"], "criminals_count": 45, "safety_status": "A+"}
{"id": 103691109360, "locations_block": ["The Complex Hollywood", "The Renberg Theatre", "Liberate Hollywood", "Luchini Pizzeria & Bar", "Hollywood Casting and Film", "Wanderlust Hollywood", "The Montalban Theatre", "Station 1640", "6555 Hollywood Blvd", "APL Restaurant", "Sound Nightclub", "Hollywood Forever Cemetery", "Avalon Hollywood", "JAPAN HOUSE Los Angeles, Level 5 Salon", "Academy Nightclub", "The Hollywood Roosevelt"], "criminals_count": 98871, "safety_status": "C"}
{"id": 104036268944, "locations_block": ["Ahmanson Recruit Training Center", "Renaissance Los Angeles Airport Hotel"], "criminals_count": 21789, "safety_status": "B"}
{"id": 104036269392, "locations_block": ["Mission Street Yoga"], "criminals_count": 6082, "safety_status": "A"}
{"id": 104036269392, "locations_block": ["The Southern Temple", "The Beverly Hilton"], "criminals_count": 28223, "safety_status": "B"}
{"id": 104036269872, "locations_block": ["ARRI Inc. | Creative Space", "MUD Studio LA"], "criminals_count": 305, "safety_status": "A"}
{"id": 104036269872, "locations_block": ["Bell Community Center Hall"], "criminals_count": 4, "safety_status": "A+"}
{"id": 104036269872, "locations_block": ["The Belasco Theater", "South Park Center", "The Theatre at Ace Hotel", "Hudson Loft", "Globe Theatre Los Angeles", "Seven Grand", "Microsoft Theater", "Central Library (then Industriel Farm for mixer)", "Exchange LA", "Exchange L.A.", "InterContinental Los Angeles Downtown", "515 South Flower Street", "The Last Bookstore", "The Midnight Mission", "Pico Union Project", "The Emerson (Next door to Broad Museum)", "Downtown Independent Theater", "California Community Foundation", "Walt Disney Concert Hall", "Casa Vertigo", "Los Angeles"], "criminals_count": 163939, "safety_status": "D"}
{"id": 103691109360, "locations_block": ["Casa Vertigo", "Pico Union Project", "Microsoft Theater", "Hudson Loft", "South Park Center", "The Belasco Theater"], "criminals_count": 163693, "safety_status": "D"}
{"id": 104036268944, "locations_block": ["JAPAN HOUSE Los Angeles, Level 5 Salon", "The Hollywood Roosevelt", "Sound Nightclub", "Wanderlust Hollywood", "6555 Hollywood Blvd", "The Renberg Theatre", "Luchini Pizzeria & Bar", "Station 1640", "Liberate Hollywood", "Hollywood Casting and Film", "Avalon Hollywood", "The Montalban Theatre", "APL Restaurant", "The Complex Hollywood", "Academy Nightclub"], "criminals_count": 76598, "safety_status": "C"}
{"id": 104036268944, "locations_block": ["MadAve", "Shatto Recreation Center & Park", "Los Angeles Celebrations Banquet Halls", "LA Celebrations Banquet Halls", "Los Globos", "Dynasty Typewriter at The Hayworth", "CCCM Mexican Center for Culture and Cinematic Arts", "Bootleg Theater"], "criminals_count": 146638, "safety_status": "D"}
{"id": 104036268944, "locations_block": ["APL Restaurant", "The Montalban Theatre", "Avalon Hollywood", "Station 1640", "Liberate Hollywood", "Luchini Pizzeria & Bar", "Academy Nightclub", "6555 Hollywood Blvd", "Sound Nightclub", "The Complex Hollywood", "Wanderlust Hollywood", "JAPAN HOUSE Los Angeles, Level 5 Salon", "Hollywood Forever Cemetery", "The Renberg Theatre", "The Hollywood Roosevelt", "Assistance League Theatre", "Hollywood Casting and Film"], "criminals_count": 89034, "safety_status": "C"}
{"id": 104036269872, "locations_block": ["Edge Studios & Grip", "EDGE Studios & Grip", "Diamond Way Buddhist Center Los Angeles", "Catch One"], "criminals_count": 72291, "safety_status": "C"}
{"id": 103691109360, "locations_block": ["The Italian American Museum of Los Angeles", "Los Angeles City Hall - Tom Bradley Tower", "The Institute for Art and Olfaction - Chinatown", "Los Angeles", "Boomtown Brewery", "Downtown Independent Theater", "Walt Disney Concert Hall", "Art Share L.A.", "The Emerson (Next door to Broad Museum)", "A+D Architecture and Design Museum", "The Last Bookstore", "California Community Foundation", "The Midnight Mission", "Exchange L.A.", "Exchange LA"], "criminals_count": 112652, "safety_status": "D"}
{"id": 104036270000, "locations_block": ["Los Angeles", "Los Angeles City Hall - Tom Bradley Tower", "Downtown Independent Theater", "Walt Disney Concert Hall", "The Last Bookstore", "The Emerson (Next door to Broad Museum)", "The Italian American Museum of Los Angeles", "Exchange L.A.", "Exchange LA", "The Midnight Mission", "Art Share L.A.", "Boomtown Brewery", "California Community Foundation", "A+D Architecture and Design Museum", "Central Library (then Industriel Farm for mixer)", "515 South Flower Street", "Seven Grand", "Globe Theatre Los Angeles", "The Institute for Art and Olfaction - Chinatown", "InterContinental Los Angeles Downtown", "The Theatre at Ace Hotel", "The Belasco Theater"], "criminals_count": 126698, "safety_status": "D"}
{"id": 104036270000, "locations_block": ["Station 1640", "Luchini Pizzeria & Bar", "Liberate Hollywood", "The Montalban Theatre", "Avalon Hollywood", "APL Restaurant", "6555 Hollywood Blvd", "Sound Nightclub", "Academy Nightclub", "The Complex Hollywood", "Wanderlust Hollywood", "JAPAN HOUSE Los Angeles, Level 5 Salon", "The Renberg Theatre", "The Hollywood Roosevelt", "Hollywood Casting and Film", "Hollywood Forever Cemetery", "Assistance League Theatre"], "criminals_count": 87133, "safety_status": "C"}
